name: Workflow
on:

  env: 
    var: "Hello"
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo $var # Hello, world!
  job_3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: My py
        run: python yes/**
        #run: echo $var

  # job_2:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #     - name: My python 
  #       run: python my_script.py

  
  #       # run: | 
  #       #     cd yes    
  #       #   python a/**
  
  # job_4:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run a one-line script
  #       run: echo I #am self-hosted runner.
